May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Cloud-init v. 19.3-46.amzn2 running 'init-local' at Tue, 30 May 2023 22:04:17 +0000. Up 9.42 seconds.
May 30 22:04:17 cloud-init[1924]: main.py[DEBUG]: No kernel command line url found.
May 30 22:04:17 cloud-init[1924]: main.py[DEBUG]: Closing stdin.
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
May 30 22:04:17 cloud-init[1924]: handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
May 30 22:04:17 cloud-init[1924]: stages.py[DEBUG]: no cache found
May 30 22:04:17 cloud-init[1924]: handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
May 30 22:04:17 cloud-init[1924]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 30 22:04:17 cloud-init[1924]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
May 30 22:04:17 cloud-init[1924]: __init__.py[DEBUG]: Searching for local data source in: []
May 30 22:04:17 cloud-init[1924]: main.py[DEBUG]: No local datasource found
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 30 22:04:17 cloud-init[1924]: stages.py[DEBUG]: network config disabled by system_cfg
May 30 22:04:17 cloud-init[1924]: stages.py[INFO]: network config is disabled by system_cfg
May 30 22:04:17 cloud-init[1924]: main.py[DEBUG]: [local] Exiting without datasource
May 30 22:04:17 cloud-init[1924]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpOpnrCj) - w: [644] 488 bytes/chars
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
May 30 22:04:17 cloud-init[1924]: util.py[DEBUG]: cloud-init mode 'init' took 0.125 seconds (0.13)
May 30 22:04:17 cloud-init[1924]: handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Cloud-init v. 19.3-46.amzn2 running 'init' at Tue, 30 May 2023 22:04:18 +0000. Up 10.85 seconds.
May 30 22:04:18 cloud-init[2248]: main.py[DEBUG]: No kernel command line url found.
May 30 22:04:18 cloud-init[2248]: main.py[DEBUG]: Closing stdin.
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
May 30 22:04:18 cloud-init[2248]: main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
May 30 22:04:18 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
May 30 22:04:18 cloud-init[2248]: stages.py[DEBUG]: no cache found
May 30 22:04:18 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
May 30 22:04:18 cloud-init[2248]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 30 22:04:18 cloud-init[2248]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
May 30 22:04:18 cloud-init[2248]: __init__.py[DEBUG]: Searching for network data source in: [u'DataSourceEc2', u'DataSourceNone']
May 30 22:04:18 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
May 30 22:04:18 cloud-init[2248]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
May 30 22:04:18 cloud-init[2248]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 1305 bytes from /proc/self/status
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_uuid (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_uuid
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_uuid returned ec2b88a1-5ac5-1083-625a-660f5c5aa8ef
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 1305 bytes from /proc/self/status
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec2b88a1-5ac5-1083-625a-660f5c5aa8ef
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 1305 bytes from /proc/self/status
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/chassis_asset_tag
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned Amazon EC2
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 1305 bytes from /proc/self/status
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/sys_vendor
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Amazon EC2
May 30 22:04:18 cloud-init[2248]: DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.020 seconds
May 30 22:04:18 cloud-init[2248]: util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.005 seconds
May 30 22:04:18 cloud-init[2248]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
May 30 22:04:18 cloud-init[2248]: DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/api/token' with {'url': 'http://169.254.169.254/latest/api/token', 'headers': {'X-aws-ec2-metadata-token-ttl-seconds': '21600', 'User-Agent': 'Cloud-Init/19.3-46.amzn2'}, 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/api/token (200, 56b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ==', 'User-Agent': 'Cloud-Init/19.3-46.amzn2'}, 'allow_redirects': True, 'method': 'GET'} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'url': 'http://169.254.169.254/2016-09-02/user-data', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/user-data (200, 2253b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 227b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/ (200, 26b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/iam/info' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/iam/info', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/iam/info (200, 227b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/ (200, 203b) after 1 attempts
May 30 22:04:18 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/local-hostname (200, 40b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/security-groups (200, 35b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv4-cidr-blocks', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/subnet-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/subnet-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/subnet-id (200, 24b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/interface-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/interface-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/interface-id (200, 21b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/mac (200, 17b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/security-group-ids' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/security-group-ids', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/security-group-ids (200, 20b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/local-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/local-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/local-ipv4s (200, 10b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/owner-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/owner-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/owner-id (200, 12b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/subnet-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/subnet-ipv4-cidr-block (200, 12b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv6-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv6-cidr-blocks', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-ipv6-cidr-blocks (200, 29b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/device-number' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/device-number', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/device-number (200, 1b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/06:73:ed:a4:cc:57/vpc-id (200, 21b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 10b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 40b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 35b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 40b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 9b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 32b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 475b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1163b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'headers': {'X-aws-ec2-metadata-token': 'AQAEAH0KXW-IgHx9wR2ESz9R8K6GmzcLNPl7opcxNDryelAWFIWbEQ=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
May 30 22:04:19 cloud-init[2248]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1483b) after 1 attempts
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Crawl of metadata service took 0.307 seconds
May 30 22:04:19 cloud-init[2248]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpzpdqoe) - w: [644] 6471 bytes/chars
May 30 22:04:19 cloud-init[2248]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpnGV0q7) - w: [600] 6471 bytes/chars
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
May 30 22:04:19 cloud-init[2248]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 1696 bytes from /etc/cloud/cloud.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 1696 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 29 bytes from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 29 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: loaded blob returned None, returning default.
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0e4a37f9a4af916e5'
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0e4a37f9a4af916e5/datasource (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/datasource - wb: [644] 29 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 13825 bytes
May 30 22:04:19 cloud-init[2248]: main.py[DEBUG]: [net] init will now be targeting instance id: i-0e4a37f9a4af916e5. new=True
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 1696 bytes from /etc/cloud/cloud.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 1696 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 29 bytes from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 29 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: loaded blob returned None, returning default.
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: network config disabled by system_cfg
May 30 22:04:19 cloud-init[2248]: stages.py[INFO]: network config is disabled by system_cfg
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/user-data.txt - wb: [600] 2253 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/user-data.txt.i - wb: [600] 2469 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/vendor-data.txt - wb: [600] 0 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/vendor-data.txt.i - wb: [600] 345 bytes
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 30 22:04:19 cloud-init[2248]: cc_set_hostname.py[DEBUG]: Setting the hostname to ip-10-0-37-87.us-east-2.compute.internal (ip-10-0-37-87)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-10-0-37-87.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-10-0-37-87.us-east-2.compute.internal
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['hostname', 'ip-10-0-37-87.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpyiDFML) - w: [644] 87 bytes/chars
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/consume_data - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/consume_data'>)
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
May 30 22:04:19 cloud-init[2248]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Added default handler for set(['text/jinja2']) from JinjaTemplatePartHandler: [['text/jinja2']]
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="part-001"'}
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, part-001, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/part-001 - wb: [700] 2124 bytes
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/cloud-config.txt - wb: [600] 0 bytes
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: no vendordata from datasource
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 1696 bytes from /etc/cloud/cloud.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 1696 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 29 bytes from /etc/cloud/cloud.cfg.d/20_amazonlinux_repo_https.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 29 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: loaded blob returned None, returning default.
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: loaded blob returned None, returning default.
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: loaded blob returned None, returning default.
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 17880 bytes
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
May 30 22:04:19 cloud-init[2248]: main.py[DEBUG]: no di_report found in config.
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f55ff2b6710>)
May 30 22:04:19 cloud-init[2248]: cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f55ff2b6610>)
May 30 22:04:19 cloud-init[2248]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_write_files - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_write_files'>)
May 30 22:04:19 cloud-init[2248]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_write_metadata - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_write_metadata'>)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module amazonlinux_repo_https (<module 'cloudinit.config.cc_amazonlinux_repo_https' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_amazonlinux_repo_https.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-amazonlinux_repo_https: running config-amazonlinux_repo_https with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_amazonlinux_repo_https - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-amazonlinux_repo_https using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_amazonlinux_repo_https'>)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['amazon-linux-https', 'enable'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-amazonlinux_repo_https: SUCCESS: config-amazonlinux_repo_https ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f55ff2b6090>)
May 30 22:04:19 cloud-init[2248]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/2248/mountinfo (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2561 bytes from /proc/2248/mountinfo
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 1306 bytes from /proc/self/status
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['growpart', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: resize_devices took 0.304 seconds
May 30 22:04:19 cloud-init[2248]: cc_growpart.py[INFO]: '/' resized: changed (/dev/nvme0n1, 1) from 4292853248 to 53684977152
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f55ff5bee10>)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/2248/mountinfo (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 2561 bytes from /proc/2248/mountinfo
May 30 22:04:19 cloud-init[2248]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 1306 bytes from /proc/self/status
May 30 22:04:19 cloud-init[2248]: cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Forked child 2424 who will run callback log_time
May 30 22:04:19 cloud-init[2248]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-set-hostname: running config-set-hostname with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_set_hostname - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_set_hostname'>)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 87 bytes from /var/lib/cloud/data/set-hostname
May 30 22:04:19 cloud-init[2248]: cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-set-hostname: SUCCESS: config-set-hostname ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-update-hostname: running config-update-hostname with frequency always
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f55ff1c32d0>)
May 30 22:04:19 cloud-init[2248]: cc_update_hostname.py[DEBUG]: Updating hostname to ip-10-0-37-87.us-east-2.compute.internal (ip-10-0-37-87)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2424]: util.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: __init__.py[DEBUG]: Attempting to update hostname to ip-10-0-37-87.us-east-2.compute.internal in 1 files
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 40 bytes
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-update-hostname: SUCCESS: config-update-hostname ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-update-etc-hosts: running config-update-etc-hosts with frequency always
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f55ff1c3210>)
May 30 22:04:19 cloud-init[2248]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-update-etc-hosts: SUCCESS: config-update-etc-hosts ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_rsyslog - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_rsyslog'>)
May 30 22:04:19 cloud-init[2248]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_users_groups - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_users_groups'>)
May 30 22:04:19 cloud-init[2248]: __init__.py[INFO]: User ec2-user already exists, skipping.
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 4328 bytes from /etc/sudoers
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_ssh - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_ssh'>)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
May 30 22:04:19 cloud-init[2424]: util.py[DEBUG]: backgrounded Resizing took 0.191 seconds
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 4034 bytes from /etc/ssh/sshd_config
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 4034 bytes from /etc/ssh/sshd_config
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
May 30 22:04:19 cloud-init[2248]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: start: init-network/config-resolv-conf: running config-resolv-conf with frequency once-per-instance
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_resolv_conf - wb: [644] 20 bytes
May 30 22:04:19 cloud-init[2248]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_resolv_conf'>)
May 30 22:04:19 cloud-init[2248]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network/config-resolv-conf: SUCCESS: config-resolv-conf ran successfully
May 30 22:04:19 cloud-init[2248]: main.py[DEBUG]: Ran 14 modules with 0 failures
May 30 22:04:19 cloud-init[2248]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpcuK1_F) - w: [644] 525 bytes/chars
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 30 22:04:19 cloud-init[2248]: util.py[DEBUG]: cloud-init mode 'init' took 1.297 seconds (1.30)
May 30 22:04:19 cloud-init[2248]: handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Cloud-init v. 19.3-46.amzn2 running 'modules:config' at Tue, 30 May 2023 22:04:20 +0000. Up 12.75 seconds.
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disk_setup.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-disk_setup: running config-disk_setup with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_disk_setup - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_disk_setup'>)
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-disk_setup: SUCCESS: config-disk_setup ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-mounts: running config-mounts with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_mounts - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_mounts'>)
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: mounts configuration is [['ephemeral0', '/media/ephemeral0'], ['swap', 'none', 'swap', 'sw', '0', '0']]
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Read 91 bytes from /etc/fstab
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
May 30 22:04:20 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
May 30 22:04:20 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: changed swap => None
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
May 30 22:04:20 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
May 30 22:04:20 cloud-init[2452]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: changed default device swap => None
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: no need to setup swap
May 30 22:04:20 cloud-init[2452]: cc_mounts.py[DEBUG]: No modifications to fstab needed
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-mounts: SUCCESS: config-mounts ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_locale - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_locale'>)
May 30 22:04:20 cloud-init[2452]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Read 93 bytes from /etc/locale.conf
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 93 bytes
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_set_passwords - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_set_passwords'>)
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Read 4034 bytes from /etc/ssh/sshd_config
May 30 22:04:20 cloud-init[2452]: ssh_util.py[DEBUG]: line 63: option PasswordAuthentication already set to no
May 30 22:04:20 cloud-init[2452]: cc_set_passwords.py[DEBUG]: No need to restart ssh service, PasswordAuthentication not updated.
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-yum-configure: running config-yum-configure with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_yum_configure - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_yum_configure'>)
May 30 22:04:20 cloud-init[2452]: cc_yum_configure.py[DEBUG]: Generating default repo files
May 30 22:04:20 cloud-init[2452]: __init__.py[DEBUG]: filtered distro mirror info: {}
May 30 22:04:20 cloud-init[2452]: cc_yum_configure.py[DEBUG]: mirror_info: {}
May 30 22:04:20 cloud-init[2452]: cc_yum_configure.py[DEBUG]: No mirror info found; ignoring.
May 30 22:04:20 cloud-init[2452]: cc_yum_configure.py[INFO]: No releasever provided, leaving yum.conf unchanged.
May 30 22:04:20 cloud-init[2452]: cc_yum_configure.py[INFO]: No repo target provided, leaving target unchanged.
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-yum-configure: SUCCESS: config-yum-configure ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_yum_add_repo - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_yum_add_repo'>)
May 30 22:04:20 cloud-init[2452]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_timezone - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_timezone'>)
May 30 22:04:20 cloud-init[2452]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fc417d60c90>)
May 30 22:04:20 cloud-init[2452]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
May 30 22:04:20 cloud-init[2452]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_runcmd - wb: [644] 20 bytes
May 30 22:04:20 cloud-init[2452]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_runcmd'>)
May 30 22:04:20 cloud-init[2452]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
May 30 22:04:20 cloud-init[2452]: main.py[DEBUG]: Ran 9 modules with 0 failures
May 30 22:04:20 cloud-init[2452]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpUPffL6) - w: [644] 551 bytes/chars
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 30 22:04:20 cloud-init[2452]: util.py[DEBUG]: cloud-init mode 'modules' took 0.175 seconds (0.18)
May 30 22:04:20 cloud-init[2452]: handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
May 30 22:04:21 cloud-init[2511]: util.py[DEBUG]: Cloud-init v. 19.3-46.amzn2 running 'modules:final' at Tue, 30 May 2023 22:04:21 +0000. Up 13.32 seconds.
May 30 22:04:21 cloud-init[2511]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 30 22:04:21 cloud-init[2511]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
May 30 22:04:21 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 20 bytes
May 30 22:04:21 cloud-init[2511]: helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
May 30 22:04:21 cloud-init[2511]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
May 30 22:04:21 cloud-init[2511]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f6285f40d50>)
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
May 30 22:04:21 cloud-init[2511]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
May 30 22:04:21 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_scripts_per_instance - wb: [644] 20 bytes
May 30 22:04:21 cloud-init[2511]: helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_scripts_per_instance'>)
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
May 30 22:04:21 cloud-init[2511]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
May 30 22:04:21 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
May 30 22:04:21 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_scripts_user - wb: [644] 20 bytes
May 30 22:04:21 cloud-init[2511]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_scripts_user'>)
May 30 22:04:21 cloud-init[2511]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
May 30 22:04:37 cloud-init[2511]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_ssh_authkey_fingerprints - wb: [644] 20 bytes
May 30 22:04:37 cloud-init[2511]: helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_ssh_authkey_fingerprints'>)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Read 4034 bytes from /etc/ssh/sshd_config
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
May 30 22:04:37 cloud-init[2511]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_keys_to_console - wb: [644] 20 bytes
May 30 22:04:37 cloud-init[2511]: helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_keys_to_console'>)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
May 30 22:04:37 cloud-init[2511]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_phone_home - wb: [644] 20 bytes
May 30 22:04:37 cloud-init[2511]: helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_phone_home'>)
May 30 22:04:37 cloud-init[2511]: cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
May 30 22:04:37 cloud-init[2511]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
May 30 22:04:37 cloud-init[2511]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f6285fa5cd0>)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Cloud-init v. 19.3-46.amzn2 finished at Tue, 30 May 2023 22:04:37 +0000. Datasource DataSourceEc2.  Up 30.04 seconds
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 59 bytes
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
May 30 22:04:37 cloud-init[2511]: stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_power_state_change.pyc'>) with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_power_state_change - wb: [644] 20 bytes
May 30 22:04:37 cloud-init[2511]: helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-0e4a37f9a4af916e5/sem/config_power_state_change'>)
May 30 22:04:37 cloud-init[2511]: cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
May 30 22:04:37 cloud-init[2511]: main.py[DEBUG]: Ran 9 modules with 0 failures
May 30 22:04:37 cloud-init[2511]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp8Pi42S) - w: [644] 577 bytes/chars
May 30 22:04:37 cloud-init[2511]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpL22TQG) - w: [644] 65 bytes/chars
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 30 22:04:37 cloud-init[2511]: util.py[DEBUG]: cloud-init mode 'modules' took 16.736 seconds (16.74)
May 30 22:04:37 cloud-init[2511]: handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final